 create table telbook ( countryzone varchar ( 36 ) NULL , institid char ( 36 ) NULL , sex varchar ( 50 ) NULL , office varchar ( 100 ) NULL , peoname varchar ( 50 ) NOT NULL , peocode varchar ( 100 ) NOT NULL , tel varchar ( 100 ) NULL , email varchar ( 100 ) NULL , worktel varchar ( 100 ) NULL , id char ( 36 ) NOT NULL , CONSTRAINT PK_TELBOOK PRIMARY KEY ( id ) , ts datetime NULL , dr smallint default 0 );
 create table instit ( parent_id varchar ( 36 ) NULL , instit_type varchar ( 10 ) NULL , instit_name varchar ( 200 ) NOT NULL , creator varchar ( 20 ) NULL , instit_code varchar ( 200 ) NOT NULL , email varchar ( 50 ) NULL , short_name varchar ( 50 ) NULL , creationtime datetime NULL , institid char ( 36 ) NOT NULL , CONSTRAINT PK_INSTIT PRIMARY KEY ( institid ) , ts datetime NULL , dr smallint default 0 );
 
 
 create table cardTableMeta ( tag varchar ( 50 ) NULL , radiodataassociate varchar ( 50 ) NULL , radiodatacontroller varchar ( 50 ) NULL , code varchar ( 50 ) NULL , name varchar ( 100 ) NULL , combodatamodel varchar ( 50 ) NULL , gateway varchar ( 50 ) NULL , createtime datetime NULL , pk_system char ( 36 ) NOT NULL , CONSTRAINT PK_CARDTABLEMETA PRIMARY KEY ( pk_system ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_countryzone ( name varchar ( 200 ) NULL , description varchar ( 100 ) NULL , pk_lang varchar ( 50 ) NULL , code varchar ( 40 ) NULL , modifier varchar ( 50 ) NULL , pk_timezone varchar ( 20 ) NULL , creator varchar ( 50 ) NULL , phonecode varchar ( 20 ) NULL , wholename varchar ( 200 ) NULL , creationtime datetime NULL , modifiedtime datetime NULL , pk_country char ( 36 ) NOT NULL , CONSTRAINT PK_BD_COUNTRYZONE PRIMARY KEY ( pk_country ) , ts datetime NULL , dr smallint default 0 );
 
 
  create table dept ( parent_id varchar ( 36 ) NULL , dept_type varchar ( 20 ) NULL , short_name varchar ( 50 ) NULL , creator varchar ( 20 ) NULL , dept_name varchar ( 50 ) NULL , dept_code varchar ( 40 ) NOT NULL , org_id varchar ( 50 ) NOT NULL , createdate datetime NULL , deptcanceldate datetime NULL , creationtime datetime NULL , pk_dept char ( 36 ) NOT NULL , CONSTRAINT PK_DEPT PRIMARY KEY ( pk_dept ) , ts datetime NULL , dr smallint default 0 );
 
 
  create table org ( parent_id varchar ( 36 ) NULL , creator varchar ( 20 ) NULL , org_type varchar ( 10 ) NULL , org_code varchar ( 200 ) NOT NULL , org_name varchar ( 200 ) NOT NULL , email varchar ( 50 ) NULL , short_name varchar ( 50 ) NULL , creationtime datetime NULL , org_id char ( 36 ) NOT NULL , CONSTRAINT PK_ORG PRIMARY KEY ( org_id ) , ts datetime NULL , dr smallint default 0 );
 
 
  create table sys_dict_type_meta ( creator varchar ( 20 ) NULL , modifier_id varchar ( 40 ) NULL , dict_type_name varchar ( 100 ) NULL , dict_type_code varchar ( 100 ) NULL , creator_id varchar ( 40 ) NULL , is_fixed varchar ( 50 ) NULL , modifier varchar ( 20 ) NULL , remark varchar ( 512 ) NULL , create_time datetime NULL , modify_time datetime NULL , dict_id char ( 36 ) NOT NULL , CONSTRAINT PK_DICT_TYPE_META PRIMARY KEY ( dict_id ) , ts datetime NULL , dr smallint default 0 );

 
  create table sys_user ( org_id char ( 36 ) NOT NULL , sex_id varchar ( 50 ) NULL , status_id varchar ( 1000 ) NULL , remark varchar ( 512 ) NULL , user_mobile varchar ( 16 ) NULL , level_name varchar ( 16 ) NULL , user_code varchar ( 32 ) NULL , creator varchar ( 20 ) NULL , modifier_id varchar ( 40 ) NULL , certificate_code varchar ( 32 ) NULL , image_url varchar ( 64 ) NULL , certificate_id varchar ( 1000 ) NULL , certificate_name varchar ( 16 ) NULL , org_name varchar ( 64 ) NULL , user_email varchar ( 64 ) NULL , user_password varchar ( 64 ) NULL , user_name varchar ( 20 ) NULL , creator_id varchar ( 40 ) NULL , modifier varchar ( 20 ) NULL , platform_id varchar ( 1000 ) NULL , level_id varchar ( 1000 ) NULL , login_name varchar ( 64 ) NULL , platform_name varchar ( 16 ) NULL , status_name varchar ( 16 ) NULL , birthdate datetime NULL , modify_time datetime NULL , create_time datetime NULL , register_date datetime NULL , id char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_USER PRIMARY KEY ( id ) , ts datetime NULL , dr smallint default 0 );
create table sys_user_job ( dept_id char ( 36 ) NOT NULL , org_id char ( 36 ) NOT NULL , creator varchar ( 20 ) NOT NULL , creator_id varchar ( 40 ) NOT NULL , is_default varchar ( 50 ) NOT NULL , is_active varchar ( 50 ) NULL , modifier varchar ( 20 ) NULL , modifier_id varchar ( 40 ) NULL , user_name varchar ( 24 ) NOT NULL , user_job_note varchar ( 256 ) NULL , user_id varchar ( 40 ) NOT NULL , modify_time datetime NULL , create_time datetime NOT NULL , id char ( 36 ) NOT NULL , fk_id_sys_user_job char ( 36 ) NULL , CONSTRAINT PK_SYS_USER_JOB PRIMARY KEY ( id ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_agent ( agentmemo varchar ( 500 ) NULL , agentname varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , district varchar ( 50 ) NULL , agentcode varchar ( 50 ) NULL , ownerid varchar ( 50 ) NULL , province varchar ( 50 ) NULL , createdate varchar ( 50 ) NULL , owner varchar ( 50 ) NULL , city varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , agentid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_AGENT PRIMARY KEY ( agentid ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_customer ( note varchar ( 500 ) NULL , phone varchar ( 50 ) NULL , address varchar ( 50 ) NULL , name varchar ( 50 ) NULL , linkman varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , sourcetype1 varchar ( 50 ) NULL , createdate varchar ( 50 ) NULL , sourcetype varchar ( 50 ) NULL , linkphone varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , sex int NULL , customerid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_CUSTOMER PRIMARY KEY ( customerid ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_material ( code varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , spec varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , note varchar ( 500 ) NULL , model varchar ( 50 ) NULL , name varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , price decimal ( 28 , 8 ) NULL , cost decimal ( 28 , 8 ) NULL , id char ( 36 ) NOT NULL , CONSTRAINT PK_BD_MATERIAL PRIMARY KEY ( id ) , ts datetime NULL , dr smallint default 0 );

 
  create table bill_deal ( surveydate varchar ( 50 ) NULL , contract varchar ( 50 ) NULL , vbillcode varchar ( 50 ) NULL , customerid varchar ( 50 ) NULL , sourcetype varchar ( 50 ) NULL , agentname varchar ( 50 ) NULL , ownerid varchar ( 50 ) NULL , community varchar ( 500 ) NULL , houseid varchar ( 50 ) NULL , agentid varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , issurvey varchar ( 50 ) NULL , dbilldate varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , picc varchar ( 50 ) NULL , owner varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , customer varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , paystate int NULL , state int NULL , totalmny decimal ( 28 , 8 ) NULL , payment decimal ( 28 , 8 ) NULL , billid char ( 36 ) NOT NULL , CONSTRAINT PK_BILL_DEAL PRIMARY KEY ( billid ) , ts datetime NULL , dr smallint default 0 );

 
  create table bill_order_b1 ( fk_id_billorderproductbody char ( 36 ) NULL , itemid varchar ( 50 ) NULL , isselected varchar ( 50 ) NULL , orderid varchar ( 50 ) NULL , itemname varchar ( 50 ) NULL , amount decimal ( 28 , 8 ) NULL , num decimal ( 28 , 8 ) NULL , price decimal ( 28 , 8 ) NULL , billbid char ( 36 ) NOT NULL , CONSTRAINT PK_BILL_ORDER_B1 PRIMARY KEY ( billbid ) , ts datetime NULL , dr smallint default 0 );
create table bill_order_b2 ( fk_id_billordermaterialbody char ( 36 ) NULL , billid varchar ( 50 ) NULL , material varchar ( 50 ) NULL , materialid varchar ( 50 ) NULL , price decimal ( 28 , 8 ) NULL , num decimal ( 28 , 8 ) NULL , amount decimal ( 28 , 8 ) NULL , billbid char ( 36 ) NOT NULL , CONSTRAINT PK_BILL_ORDER_B2 PRIMARY KEY ( billbid ) , ts datetime NULL , dr smallint default 0 );
create table bill_order ( vbillcode varchar ( 50 ) NULL , customerid varchar ( 50 ) NULL , customer varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , agentid varchar ( 50 ) NULL , serviceid varchar ( 50 ) NULL , product varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , agentname varchar ( 50 ) NULL , dbilldate varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , orgname varchar ( 50 ) NULL , dealid varchar ( 50 ) NULL , productid varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , state int NULL , paystate int NULL , type int NULL , prostate int NULL , totalmny decimal ( 28 , 8 ) NULL , materialcosts decimal ( 28 , 8 ) NULL , num decimal ( 28 , 8 ) NULL , price decimal ( 28 , 8 ) NULL , servicecharge decimal ( 28 , 8 ) NULL , billid char ( 36 ) NOT NULL , CONSTRAINT PK_BILL_ORDER PRIMARY KEY ( billid ) , ts datetime NULL , dr smallint default 0 );

 
  create table bill_service_procedure ( fk_id_serviceprocedure char ( 36 ) NULL , type varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , itemid varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , itemorder varchar ( 50 ) NULL , itemname varchar ( 50 ) NULL , formid varchar ( 50 ) NULL , billid varchar ( 50 ) NULL , state int NULL , billbid char ( 36 ) NOT NULL , CONSTRAINT PK_RVICE_PROCEDURE PRIMARY KEY ( billbid ) , ts datetime NULL , dr smallint default 0 );
 create table bill_service ( surveyid varchar ( 50 ) NULL , vbillcode varchar ( 50 ) NULL , agentname varchar ( 50 ) NULL , dbilldate varchar ( 50 ) NULL , procedureid varchar ( 50 ) NULL , serverid varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , houseid varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , constructionid varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , startdate varchar ( 50 ) NULL , planneddate varchar ( 50 ) NULL , agentid varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , dealid varchar ( 50 ) NULL , note varchar ( 500 ) NULL , servername varchar ( 50 ) NULL , customerid varchar ( 50 ) NULL , supervisorid varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , supervisor varchar ( 50 ) NULL , constructionname varchar ( 50 ) NULL , enddate varchar ( 50 ) NULL , procedurename varchar ( 50 ) NULL , surveyname varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , supervisorstate int NULL , orgstate int NULL , serverstate int NULL , servicestate int NULL , materialstate int NULL , contractstate int NULL , paystate int NULL , constructionstate int NULL , agentstate int NULL , surveystate int NULL , paidamount decimal ( 28 , 8 ) NULL , materialcosts decimal ( 28 , 8 ) NULL , totalamount decimal ( 28 , 8 ) NULL , servicecharge decimal ( 28 , 8 ) NULL , billid char ( 36 ) NOT NULL , CONSTRAINT PK_BILL_SERVICE PRIMARY KEY ( billid ) , ts datetime NULL , dr smallint default 0 );
 
 
  create table bill_service_payment ( auditnote varchar ( 50 ) NULL , auditor varchar ( 50 ) NULL , billnote varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , audittime varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , neworderid varchar ( 50 ) NULL , oldorderid varchar ( 50 ) NULL , vbillcode varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , agentid varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , agentname varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , auditorid varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , billid varchar ( 50 ) NULL , serialnum varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , auditstate int default 0 NULL , type int default 0 NULL , paymoney decimal ( 28 , 8 ) default 0 NULL , paymentid char ( 36 ) NOT NULL , CONSTRAINT PK_SERVICE_PAYMENT PRIMARY KEY ( paymentid ) , ts datetime NULL , dr smallint default 0 );
 
 
  create table sys_billcodemanage ( orgname varchar ( 50 ) NULL , billtype varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , dbilldate varchar ( 50 ) NULL , serial int NULL , manageid char ( 36 ) NOT NULL , CONSTRAINT PK_BILLCODEMANAGE PRIMARY KEY ( manageid ) , ts datetime NULL , dr smallint default 0 );
 
 
  create table bd_construction ( agent varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , teamurl varchar ( 255 ) NULL , agentid varchar ( 50 ) NULL , owner varchar ( 50 ) NULL , jobscope varchar ( 50 ) NULL , teamname varchar ( 50 ) NULL , teammemo varchar ( 500 ) NULL , phone varchar ( 50 ) NULL , ownerid varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , id char ( 36 ) NOT NULL , CONSTRAINT PK_BD_CONSTRUCTION PRIMARY KEY ( id ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_contract ( policyphoto varchar ( 1000 ) NULL , invoiceelecvers varchar ( 50 ) NULL , invoicestate varchar ( 50 ) NULL , agentname varchar ( 50 ) NULL , invoicephoto varchar ( 1000 ) NULL , contractphoto varchar ( 1000 ) NULL , contractdocunum varchar ( 50 ) NULL , policydocunum varchar ( 50 ) NULL , serviceid varchar ( 50 ) NULL , servicecode varchar ( 50 ) NULL , customername varchar ( 50 ) NULL , policyelecvers varchar ( 50 ) NULL , invoicemailstate varchar ( 50 ) NULL , contractelecvers varchar ( 50 ) NULL , picc varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , invoicedocunum varchar ( 50 ) NULL , contractcode varchar ( 50 ) NULL , dealid varchar ( 50 ) NULL , address varchar ( 50 ) NULL , idnumber varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , contractmailstate varchar ( 50 ) NULL , telphone varchar ( 50 ) NULL , agentid varchar ( 50 ) NULL , dealpaystate varchar ( 50 ) NULL , postalnum varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , customerid varchar ( 50 ) NULL , paymoney varchar ( 50 ) NULL , dealcode varchar ( 50 ) NULL , policymailstate varchar ( 50 ) NULL , createtime datetime NULL , contractid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_CONTRACT PRIMARY KEY ( contractid ) , ts datetime NULL , dr smallint default 0 );

 
  create table sys_funregister ( funcode varchar ( 50 ) NULL , funicon varchar ( 50 ) NULL , parentid varchar ( 50 ) NULL , furl varchar ( 50 ) NULL , funname varchar ( 50 ) NULL , funtype int NULL , createdate datetime NULL , id char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_FUNREGISTER PRIMARY KEY ( id ) , ts datetime NULL , dr smallint default 0 );

 
  create table log_order_allot ( action varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , ownerid varchar ( 50 ) NULL , object varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , owner varchar ( 50 ) NULL , note varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , orderid varchar ( 50 ) NULL , dealid varchar ( 50 ) NULL , logid char ( 36 ) NOT NULL , CONSTRAINT PK_LOG_ORDER_ALLOT PRIMARY KEY ( logid ) , ts datetime NULL , dr smallint default 0 );

 
  create table log_order_note ( createtime varchar ( 50 ) NULL , dealid varchar ( 50 ) NULL , action varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , note varchar ( 50 ) NULL , orderid varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , logid char ( 36 ) NOT NULL , CONSTRAINT PK_LOG_ORDER_NOTE PRIMARY KEY ( logid ) , ts datetime NULL , dr smallint default 0 );

 
  create table log_service ( note varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , serviceid varchar ( 50 ) NULL , result varchar ( 50 ) NULL , action varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , logid char ( 36 ) NOT NULL , CONSTRAINT PK_LOG_SERVICE PRIMARY KEY ( logid ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_product_b ( fk_id_productbody char ( 36 ) NULL , itemname varchar ( 50 ) NULL , memo varchar ( 1000 ) NULL , productid varchar ( 50 ) NOT NULL , itemid varchar ( 50 ) NULL , type int NULL , materialcost decimal ( 28 , 8 ) default 0 NULL , servicecost decimal ( 28 , 8 ) default 0 NULL , price decimal ( 28 , 8 ) default 0 NULL , productbid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_PRODUCT_B PRIMARY KEY ( productbid ) , ts datetime NULL , dr smallint default 0 );
 create table bd_product ( modifierid varchar ( 50 ) NULL , productcode varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , productname varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , orgid varchar ( 50 ) NULL , price decimal ( 28 , 8 ) NULL , productid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_PRODUCT PRIMARY KEY ( productid ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_productitem ( modifytime varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , materialid varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , materialname varchar ( 50 ) NULL , itemname varchar ( 50 ) NULL , itemcode varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , type int NULL , servicecost decimal ( 28 , 8 ) NULL , price decimal ( 28 , 8 ) NULL , materialcost decimal ( 28 , 8 ) NULL , itemid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_PRODUCTITEM PRIMARY KEY ( itemid ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_settlement ( constructionname varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , orgid varchar ( 50 ) NULL , billid varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , constructionid varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , agentname varchar ( 50 ) NULL , money varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , type varchar ( 50 ) NULL , agentid varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , settlementid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_SETTLEMENT PRIMARY KEY ( settlementid ) , ts datetime NULL , dr smallint default 0 );

 
  create table sys_form_b ( fk_id_formb char ( 36 ) NULL , type varchar ( 50 ) NULL , displayname varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , formid varchar ( 50 ) NULL , attribute varchar ( 50 ) NULL , formbid char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_FORM_B PRIMARY KEY ( formbid ) , ts datetime NULL , dr smallint default 0 );
create table sys_form ( orgname varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , creatorid varchar ( 50 ) NULL , version varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , formname varchar ( 50 ) NULL , formcode varchar ( 50 ) NULL , formid char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_FORM PRIMARY KEY ( formid ) , ts datetime NULL , dr smallint default 0 );

 
  create table sys_form_value ( orgname varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , sid varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , formbid varchar ( 50 ) NULL , value varchar ( 500 ) NULL , modifierid varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , formid varchar ( 50 ) NULL , id char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_FORM_VALUE PRIMARY KEY ( id ) , ts datetime NULL , dr smallint default 0 );

 
  create table bd_House ( district varchar ( 50 ) NULL , address varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , createtime varchar ( 50 ) NULL , province varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , reason varchar ( 50 ) NULL , part varchar ( 50 ) NULL , type varchar ( 50 ) NULL , customerid varchar ( 50 ) NULL , city varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , area decimal ( 28 , 8 ) NULL , houseid char ( 36 ) NOT NULL , CONSTRAINT PK_BD_HOUSE PRIMARY KEY ( houseid ) , ts datetime NULL , dr smallint default 0 );

 
  create table sys_log ( orgname varchar ( 50 ) NULL , action varchar ( 50 ) NULL , object varchar ( 50 ) NULL , actcontent varchar ( 50 ) NULL , orgid varchar ( 50 ) NULL , userid varchar ( 50 ) NULL , username varchar ( 50 ) NULL , logid char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_LOG PRIMARY KEY ( logid ) , ts datetime NULL , dr smallint default 0 );
 
 
  create table sys_message ( title varchar ( 50 ) NULL , content varchar ( 500 ) NULL , senderid varchar ( 50 ) NULL , sender varchar ( 50 ) NULL , receiver varchar ( 50 ) NULL , detailurl varchar ( 50 ) NULL , messagetype varchar ( 50 ) NULL , receiverid varchar ( 50 ) NULL , state int NULL , sendtime datetime NULL , messageid char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_MESSAGE PRIMARY KEY ( messageid ) , ts datetime NULL , dr smallint default 0 );

 
  create table sys_procedure_b ( fk_id_procedurebody char ( 36 ) NULL , procedureid varchar ( 50 ) NULL , formid varchar ( 50 ) NULL , itemorder varchar ( 50 ) NULL , itemname varchar ( 50 ) NULL , memo varchar ( 500) NULL , formname varchar ( 50 ) NULL , type varchar ( 50 ) NULL , procedurebid char ( 36 ) NOT NULL , vdef2 varchar ( 101 ) NULL , vdef5 varchar ( 101 ) NULL , vdef1 varchar ( 101 ) NULL , vdef4 varchar ( 101 ) NULL , vdef3 varchar ( 101 ) NULL , CONSTRAINT PK_SYS_PROCEDURE_B PRIMARY KEY ( procedurebid ) , ts datetime NULL , dr smallint default 0 );
 create table sys_procedure ( createtime varchar ( 50 ) NULL , modifierid varchar ( 50 ) NULL , procedurecode varchar ( 50 ) NULL , memo varchar ( 500 ) NULL , orgid varchar ( 50 ) NULL , version varchar ( 50 ) NULL , modifytime varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , modifier varchar ( 50 ) NULL , orgname varchar ( 50 ) NULL , procedurename varchar ( 50 ) NULL , creatorid varchar ( 50 ) NULL , procedureid char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_PROCEDURE PRIMARY KEY ( procedureid ) , ts datetime NULL , dr smallint default 0 );

 
  create table sys_role ( rolecode varchar ( 50 ) NULL , funs varchar ( 2000 ) NULL , roletype varchar ( 50 ) NULL , rolename varchar ( 50 ) NULL , creator varchar ( 50 ) NULL , createtime datetime NULL , roleid char ( 36 ) NOT NULL , CONSTRAINT PK_SYS_ROLE PRIMARY KEY ( roleid ) , ts datetime NULL , dr smallint default 0 );

 
 