--此脚本作为元数据发布时参考使用,以便开发者了解元数据信息在数据库中的记录.
--严禁将此脚本直接或修改后在数据库中执行,如由上述行为引发问题,概不支持.


 delete from md_db_relation where startattrid in ( select id from md_property where classid in ( '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', '@@@@' ) and ( versiontype = 0 or versiontype is null ) ) and starttableid in ( 'sys_dictionary', '@@@@' );
 delete from md_ormap where ATTRIBUTEID in ( select id from md_property where classid in ( '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', '@@@@' ) and ( versiontype = 0 or versiontype is null ) ) and tableid in ( 'sys_dictionary', '@@@@' );
 delete from md_table where id not in ( select distinct tableid from md_ormap ) and ( versiontype = 0 or versiontype is null );
 delete from md_column where tableid in ( 'sys_dictionary', '@@@@' ) and id not in ( select distinct columnid from md_ormap ) and ( ifnull( groupid, '~' ) = '~' or groupid = id ) and name <> 'extend_bean_tag';
 delete from md_column where tableid in ( 'sys_dictionary', '@@@@' ) and groupid is not null and groupid not in ( select distinct t.id from ( select * from md_column ) t where tableid in ( 'sys_dictionary', '@@@@' ) );
 delete from md_db_relation where starttableid not in ( select id from md_table );
 delete from md_association where componentID = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' and ( versiontype = 0 or versiontype is null );
 delete from md_property where classID in ( select distinct id from md_class where componentID = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' ) and ( versiontype = 0 or versiontype is null );
 delete from md_bizitfmap where classID in ( select distinct id from md_class where componentID = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' );
 delete from md_bizitfmap where classID in ( select id from md_opinterface where componentID = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' and ( versiontype = 0 or versiontype is null ) );
 delete from md_accessorpara where id in ( select distinct id from md_class where componentID = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' );
 delete from md_enumvalue where id in ( select distinct id from md_class where componentID = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' ) and ( versiontype = 0 or versiontype is null );
 delete from md_class where componentID = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' and ( versiontype = 0 or versiontype is null );
 delete from md_component where id = 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a' and ( versiontype = 0 or versiontype is null );
 delete from md_table where ( id = 'sys_dictionary' );
 delete from md_column where ( id = 'sys_dictionary@@PK@@' );
 delete from md_column where ( id = 'sys_dictionary@@@value' );
 delete from md_column where ( id = 'sys_dictionary@@@type' );
 delete from md_column where ( id = 'sys_dictionary@@@parentid' );
 delete from md_column where ( id = 'sys_dictionary@@@createorid' );
 delete from md_column where ( id = 'sys_dictionary@@@createorname' );
 delete from md_column where ( id = 'sys_dictionary@@@createtime' );
 delete from md_column where ( id = 'sys_dictionary@@@modifyid' );
 delete from md_column where ( id = 'sys_dictionary@@@modifyname' );



 insert into md_component ( createtime, tenantid, resid, ts, resmodule, version, namespace, creator, fromsourcebmf, modifier, id, help, description, preload, name, ownmodule, versiontype, displayname, industry, modifytime, isbizmodel, dr ) values ( '2019-06-21 18:08:04', null, null, '2019-06-27 19:41:38', 'sys_dictionary', '3', 'dingCMS', null, 'Y', null, 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a', null, null, null, 'sys_dictionary', 'dingCMS', 0, 'sys_dictionary', '0', '2019-06-21 18:08:09', 'N', 0 );
 insert into md_class ( modinfoclassname, createtime, parentclassid, ts, userdefclassname, iscreatesql, creator, id, help, bizitfimpclassname, description, name, refmodelname, industry, modifytime, dr, accessorclassname, tenantid, isprimary, resid, isauthen, keyattribute, fullclassname, classtype, returntype, componentid, isactive, modifier, stereotype, isextendbean, defaulttablename, versiontype, displayname, precise, fixedlength ) values ( null, '2019-06-21 18:08:08', null, '2019-06-27 19:41:38', null, 'Y', null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', null, null, null, 'Dictionary', null, '0', '2019-06-21 18:15:16', 0, 'nc.md.model.access.javamap.POJOStyle', null, 'Y', null, 'Y', 'd2dadf5d-c7dc-4806-b0a6-5953e6bb1da4', 'com.yonyou.iuap.system.entity.Dictionary', 201, null, 'ae9cf26a-0aab-49d6-ab9c-b09bc078ec7a', null, null, null, null, 'sys_dictionary', 0, '系统字典', null, null );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', 'd2dadf5d-c7dc-4806-b0a6-5953e6bb1da4', null, 300, null, 'id', null, '0', null, null, 0, null, null, 'N', null, 'Y', 0, 'N', null, 'Y', 36, null, 'BS000010000100001051', 'N', null, 'N', 0, '主键', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', 'c374d9bf-407e-406f-a331-bb4d87bf4722', null, 300, null, 'value', null, '0', null, null, 0, null, null, 'N', null, 'Y', 1, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '字典值', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', '35adfb90-5509-48af-b1b7-5f9ff723cb18', null, 300, null, 'type', null, '0', null, null, 0, null, null, 'N', null, 'Y', 2, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '字典类型', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', '19f0fcb2-75e7-4e6f-9527-aa61c9df3600', null, 300, null, 'parentid', null, '0', null, null, 0, null, null, 'N', null, 'Y', 3, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '父id', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', 'c1124448-59de-4482-ad29-e0590b81edc3', null, 300, null, 'createorid', null, '0', null, null, 0, null, null, 'N', null, 'Y', 4, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '创建人id', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', 'aa2e83ca-c932-4117-8e31-d82dc65a2282', null, 300, null, 'createorname', null, '0', null, null, 0, null, null, 'N', null, 'Y', 5, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '创建人姓名', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', '888d3f23-490e-4374-a8f9-e8dc9aedaccc', null, 300, null, 'createtime', null, '0', null, null, 0, null, null, 'N', null, 'Y', 6, 'Y', null, 'Y', null, null, 'BS000010000100001033', 'N', null, 'N', 0, '创建时间', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', 'd244c373-5f46-4740-a967-4a4f81bef367', null, 300, null, 'modifyid', null, '0', null, null, 0, null, null, 'N', null, 'Y', 7, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '修改人id', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-27 19:41:38', 0, null, '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'N', null, 'N', null, 'N', '4cd65aff-0e94-4e39-95d3-cdc7111dd07e', null, 300, null, 'modifyname', null, '0', null, null, 0, null, null, 'N', null, 'Y', 8, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '修改人姓名', null, 'N' );
 insert into md_table ( createtime, tenantid, resid, ts, isextendtable, resmodule, creator, fromsourcebmf, modifier, id, isactive, help, databaseid, description, name, versiontype, industry, displayname, modifytime, parenttable, dr ) values ( '2019-06-21 18:08:08', null, null, '2019-06-27 19:41:38', 'N', 'sys_dictionary', null, 'Y', null, 'sys_dictionary', null, null, null, null, 'sys_dictionary', 0, '0', '系统字典', '2019-06-21 18:15:16', null, 0 );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@PK@@', null, 'char', null, null, 'id', null, null, null, null, 0, null, 36, null, 'Y', 'N', 'Y', null, 0, null, 0, 'sys_dictionary', '主键', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@value', null, 'varchar', null, null, 'value', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 1, null, 0, 'sys_dictionary', '字典值', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@type', null, 'varchar', null, null, 'type', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 2, null, 0, 'sys_dictionary', '字典类型', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@parentid', null, 'varchar', null, null, 'parentid', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 3, null, 0, 'sys_dictionary', '父id', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@createorid', null, 'varchar', null, null, 'createorid', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 4, null, 0, 'sys_dictionary', '创建人id', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@createorname', null, 'varchar', null, null, 'createorname', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 5, null, 0, 'sys_dictionary', '创建人姓名', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@createtime', null, 'datetime', null, null, 'createtime', null, null, null, null, 0, null, null, null, 'N', 'Y', 'Y', null, 6, null, 0, 'sys_dictionary', '创建时间', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@modifyid', null, 'varchar', null, null, 'modifyid', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 7, null, 0, 'sys_dictionary', '修改人id', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-27 19:41:38', null, 'sys_dictionary@@@modifyname', null, 'varchar', null, null, 'modifyname', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 8, null, 0, 'sys_dictionary', '修改人姓名', null );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@createorid', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', 'c1124448-59de-4482-ad29-e0590b81edc3', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@createorname', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', 'aa2e83ca-c932-4117-8e31-d82dc65a2282', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@parentid', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', '19f0fcb2-75e7-4e6f-9527-aa61c9df3600', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@modifyid', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', 'd244c373-5f46-4740-a967-4a4f81bef367', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@createtime', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', '888d3f23-490e-4374-a8f9-e8dc9aedaccc', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@modifyname', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', '4cd65aff-0e94-4e39-95d3-cdc7111dd07e', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@type', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', '35adfb90-5509-48af-b1b7-5f9ff723cb18', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@@value', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', 'c374d9bf-407e-406f-a331-bb4d87bf4722', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-27 19:41:38', 'sys_dictionary@@PK@@', '1a8eb8f6-fe5b-4352-ae85-a11b3b3f512a', 'sys_dictionary', 'd2dadf5d-c7dc-4806-b0a6-5953e6bb1da4', 0 );
