--此脚本作为元数据发布时参考使用,以便开发者了解元数据信息在数据库中的记录.
--严禁将此脚本直接或修改后在数据库中执行,如由上述行为引发问题,概不支持.


 delete from md_db_relation where startattrid in ( select id from md_property where classid in ( '8de227bc-8970-4db4-ab76-986c3fd3ee02', '@@@@' ) and ( versiontype = 0 or versiontype is null ) ) and starttableid in ( 'bd_customer', '@@@@' );
 delete from md_ormap where ATTRIBUTEID in ( select id from md_property where classid in ( '8de227bc-8970-4db4-ab76-986c3fd3ee02', '@@@@' ) and ( versiontype = 0 or versiontype is null ) ) and tableid in ( 'bd_customer', '@@@@' );
 delete from md_table where id not in ( select distinct tableid from md_ormap ) and ( versiontype = 0 or versiontype is null );
 delete from md_column where tableid in ( 'bd_customer', '@@@@' ) and id not in ( select distinct columnid from md_ormap ) and ( ifnull( groupid, '~' ) = '~' or groupid = id ) and name <> 'extend_bean_tag';
 delete from md_column where tableid in ( 'bd_customer', '@@@@' ) and groupid is not null and groupid not in ( select distinct t.id from ( select * from md_column ) t where tableid in ( 'bd_customer', '@@@@' ) );
 delete from md_db_relation where starttableid not in ( select id from md_table );
 delete from md_association where componentID = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' and ( versiontype = 0 or versiontype is null );
 delete from md_property where classID in ( select distinct id from md_class where componentID = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' ) and ( versiontype = 0 or versiontype is null );
 delete from md_bizitfmap where classID in ( select distinct id from md_class where componentID = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' );
 delete from md_bizitfmap where classID in ( select id from md_opinterface where componentID = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' and ( versiontype = 0 or versiontype is null ) );
 delete from md_accessorpara where id in ( select distinct id from md_class where componentID = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' );
 delete from md_enumvalue where id in ( select distinct id from md_class where componentID = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' ) and ( versiontype = 0 or versiontype is null );
 delete from md_class where componentID = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' and ( versiontype = 0 or versiontype is null );
 delete from md_component where id = '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a' and ( versiontype = 0 or versiontype is null );
 delete from md_table where ( id = 'bd_customer' );
 delete from md_column where ( id = 'bd_customer@@PK@@' );
 delete from md_column where ( id = 'bd_customer@@@name' );
 delete from md_column where ( id = 'bd_customer@@@sex' );
 delete from md_column where ( id = 'bd_customer@@@phone' );
 delete from md_column where ( id = 'bd_customer@@@sourcetype' );
 delete from md_column where ( id = 'bd_customer@@@sourcetype1' );
 delete from md_column where ( id = 'bd_customer@@@address' );
 delete from md_column where ( id = 'bd_customer@@@linkman' );
 delete from md_column where ( id = 'bd_customer@@@linkphone' );
 delete from md_column where ( id = 'bd_customer@@@creator' );
 delete from md_column where ( id = 'bd_customer@@@creatorid' );
 delete from md_column where ( id = 'bd_customer@@@createdate' );
 delete from md_column where ( id = 'bd_customer@@@note' );



 insert into md_component ( createtime, tenantid, resid, ts, resmodule, version, namespace, creator, fromsourcebmf, modifier, id, help, description, preload, name, ownmodule, versiontype, displayname, industry, modifytime, isbizmodel, dr ) values ( '2018-09-20 20:46:20', null, null, '2019-05-27 14:12:41', 'bd_customer', '7', 'dingCMS', null, 'Y', null, '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a', null, null, null, 'bd_customer', 'dingCMS', 0, 'bd_customer', '0', '2018-09-26 12:17:11', 'N', 0 );
 insert into md_class ( modinfoclassname, createtime, parentclassid, ts, userdefclassname, iscreatesql, creator, id, help, bizitfimpclassname, description, name, refmodelname, industry, modifytime, dr, accessorclassname, tenantid, isprimary, resid, isauthen, keyattribute, fullclassname, classtype, returntype, componentid, isactive, modifier, stereotype, isextendbean, defaulttablename, versiontype, displayname, precise, fixedlength ) values ( null, '2018-09-20 20:46:23', null, '2019-05-27 14:12:41', null, 'Y', null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', null, null, null, 'Customer', null, '0', '2018-09-26 12:17:44', 0, 'nc.md.model.access.javamap.POJOStyle', null, 'Y', null, 'Y', '5feaca35-5496-43c0-a79c-a0c4ca2a4007', 'com.ding.cms.entity.Customer', 201, null, '0bc10ee3-e50a-48a9-b5b6-9fe203b1f29a', null, null, null, null, 'bd_customer', 0, '客户', null, null );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '5feaca35-5496-43c0-a79c-a0c4ca2a4007', null, 300, null, 'customerid', null, '0', null, null, 0, null, null, 'N', null, 'Y', 0, 'N', null, 'Y', 36, null, 'BS000010000100001051', 'N', null, 'N', 0, '主键', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '7b143894-27d2-4aab-87d4-5ae167834bef', null, 300, null, 'name', null, '0', null, null, 0, null, null, 'N', null, 'Y', 1, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '客户名称', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', 'ef1b75d5-f36d-43da-b469-d625aba11f8d', null, 300, null, 'sex', null, '0', null, null, 0, null, null, 'N', null, 'Y', 2, 'Y', null, 'Y', null, null, 'BS000010000100001004', 'N', null, 'N', 0, '性别', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', 'a903ad8b-0a6e-4821-81a7-40677e08404b', null, 300, null, 'phone', null, '0', null, null, 0, null, null, 'N', null, 'Y', 3, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '手机号', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '073ec770-3d98-41d2-a7e7-05745558424b', null, 300, null, 'sourcetype', null, '0', null, null, 0, null, null, 'N', null, 'Y', 4, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '来源', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '15e8235c-fa89-4862-aeed-d3f34980c83b', null, 300, null, 'sourcetype1', null, '0', null, null, 0, null, null, 'N', null, 'Y', 5, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '二级来源', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '51668a07-7f53-4859-9b60-905215fc4b38', null, 300, null, 'address', null, '0', null, null, 0, null, null, 'N', null, 'Y', 6, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '地址', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '1c63fa7f-33a4-48be-a75d-6a33e928a809', null, 300, null, 'linkman', null, '0', null, null, 0, null, null, 'N', null, 'Y', 7, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '联系人', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '6f03e782-c863-4d60-a759-976aff743205', null, 300, null, 'linkphone', null, '0', null, null, 0, null, null, 'N', null, 'Y', 8, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '联系人电话', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', 'f37146db-968c-46c9-a599-3680858ac049', null, 300, null, 'creator', null, '0', null, null, 0, null, null, 'N', null, 'Y', 9, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '创建人', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '72049445-49cf-4939-9eb1-59f1c6e6e0fe', null, 300, null, 'creatorid', null, '0', null, null, 0, null, null, 'N', null, 'Y', 10, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '创建人id', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '6fd39e80-206f-4a06-a1c8-e154be760ae4', null, 300, null, 'createdate', null, '0', null, null, 0, null, null, 'N', null, 'Y', 11, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, '创建日期', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-05-27 14:12:41', 0, null, '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'N', null, 'N', null, 'N', '5828929e-1e74-4019-8380-1c2f1ed02d28', null, 300, null, 'note', null, '0', null, null, 0, null, null, 'N', null, 'Y', 12, 'Y', null, 'Y', 500, null, 'BS000010000100001001', 'N', null, 'N', 0, '备注', null, 'N' );
 insert into md_table ( createtime, tenantid, resid, ts, isextendtable, resmodule, creator, fromsourcebmf, modifier, id, isactive, help, databaseid, description, name, versiontype, industry, displayname, modifytime, parenttable, dr ) values ( '2018-09-20 20:46:23', null, null, '2019-05-27 14:12:41', 'N', 'bd_customer', null, 'Y', null, 'bd_customer', null, null, null, null, 'bd_customer', 0, '0', '客户', '2018-09-26 12:17:44', null, 0 );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@PK@@', null, 'char', null, null, 'customerid', null, null, null, null, 0, null, 36, null, 'Y', 'N', 'Y', null, 0, null, 0, 'bd_customer', '主键', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@name', null, 'varchar', null, null, 'name', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 1, null, 0, 'bd_customer', '客户名称', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@sex', null, 'int', null, null, 'sex', null, null, null, null, 0, null, null, null, 'N', 'Y', 'Y', null, 2, null, 0, 'bd_customer', '性别', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@phone', null, 'varchar', null, null, 'phone', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 3, null, 0, 'bd_customer', '手机号', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@sourcetype', null, 'varchar', null, null, 'sourcetype', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 4, null, 0, 'bd_customer', '来源', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@sourcetype1', null, 'varchar', null, null, 'sourcetype1', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 5, null, 0, 'bd_customer', '二级来源', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@address', null, 'varchar', null, null, 'address', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 6, null, 0, 'bd_customer', '地址', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@linkman', null, 'varchar', null, null, 'linkman', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 7, null, 0, 'bd_customer', '联系人', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@linkphone', null, 'varchar', null, null, 'linkphone', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 8, null, 0, 'bd_customer', '联系人电话', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@creator', null, 'varchar', null, null, 'creator', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 9, null, 0, 'bd_customer', '创建人', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@creatorid', null, 'varchar', null, null, 'creatorid', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 10, null, 0, 'bd_customer', '创建人id', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@createdate', null, 'varchar', null, null, 'createdate', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 11, null, 0, 'bd_customer', '创建日期', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-05-27 14:12:41', null, 'bd_customer@@@note', null, 'varchar', null, null, 'note', null, null, null, null, 0, null, 500, null, 'N', 'Y', 'Y', null, 12, null, 0, 'bd_customer', '备注', null );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@linkman', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '1c63fa7f-33a4-48be-a75d-6a33e928a809', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@address', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '51668a07-7f53-4859-9b60-905215fc4b38', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@phone', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', 'a903ad8b-0a6e-4821-81a7-40677e08404b', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@creatorid', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '72049445-49cf-4939-9eb1-59f1c6e6e0fe', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@note', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '5828929e-1e74-4019-8380-1c2f1ed02d28', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@name', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '7b143894-27d2-4aab-87d4-5ae167834bef', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@createdate', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '6fd39e80-206f-4a06-a1c8-e154be760ae4', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@linkphone', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '6f03e782-c863-4d60-a759-976aff743205', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@sex', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', 'ef1b75d5-f36d-43da-b469-d625aba11f8d', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@sourcetype1', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '15e8235c-fa89-4862-aeed-d3f34980c83b', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@PK@@', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '5feaca35-5496-43c0-a79c-a0c4ca2a4007', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@creator', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', 'f37146db-968c-46c9-a599-3680858ac049', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-05-27 14:12:41', 'bd_customer@@@sourcetype', '8de227bc-8970-4db4-ab76-986c3fd3ee02', 'bd_customer', '073ec770-3d98-41d2-a7e7-05745558424b', 0 );
