--此脚本作为元数据发布时参考使用,以便开发者了解元数据信息在数据库中的记录.
--严禁将此脚本直接或修改后在数据库中执行,如由上述行为引发问题,概不支持.


 delete from md_db_relation where startattrid in ( select id from md_property where classid in ( 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', '@@@@' ) and ( versiontype = 0 or versiontype is null ) ) and starttableid in ( 'bd_joblock', '@@@@' );
 delete from md_ormap where ATTRIBUTEID in ( select id from md_property where classid in ( 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', '@@@@' ) and ( versiontype = 0 or versiontype is null ) ) and tableid in ( 'bd_joblock', '@@@@' );
 delete from md_table where id not in ( select distinct tableid from md_ormap ) and ( versiontype = 0 or versiontype is null );
 delete from md_column where tableid in ( 'bd_joblock', '@@@@' ) and id not in ( select distinct columnid from md_ormap ) and ( ifnull( groupid, '~' ) = '~' or groupid = id ) and name <> 'extend_bean_tag';
 delete from md_column where tableid in ( 'bd_joblock', '@@@@' ) and groupid is not null and groupid not in ( select distinct t.id from ( select * from md_column ) t where tableid in ( 'bd_joblock', '@@@@' ) );
 delete from md_db_relation where starttableid not in ( select id from md_table );
 delete from md_association where componentID = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' and ( versiontype = 0 or versiontype is null );
 delete from md_property where classID in ( select distinct id from md_class where componentID = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' ) and ( versiontype = 0 or versiontype is null );
 delete from md_bizitfmap where classID in ( select distinct id from md_class where componentID = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' );
 delete from md_bizitfmap where classID in ( select id from md_opinterface where componentID = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' and ( versiontype = 0 or versiontype is null ) );
 delete from md_accessorpara where id in ( select distinct id from md_class where componentID = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' );
 delete from md_enumvalue where id in ( select distinct id from md_class where componentID = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' ) and ( versiontype = 0 or versiontype is null );
 delete from md_class where componentID = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' and ( versiontype = 0 or versiontype is null );
 delete from md_component where id = '6a5d90af-8b8f-4613-9e08-40f90d2d8b39' and ( versiontype = 0 or versiontype is null );
 delete from md_table where ( id = 'bd_joblock' );
 delete from md_column where ( id = 'bd_joblock@@PK@@' );
 delete from md_column where ( id = 'bd_joblock@@@jobid' );
 delete from md_column where ( id = 'bd_joblock@@@starttime' );
 delete from md_column where ( id = 'bd_joblock@@@ip' );



 insert into md_component ( createtime, tenantid, resid, ts, resmodule, version, namespace, creator, fromsourcebmf, modifier, id, help, description, preload, name, ownmodule, versiontype, displayname, industry, modifytime, isbizmodel, dr ) values ( '2019-06-06 16:42:37', null, null, '2019-06-06 16:48:41', 'bd_JobLock', '1', 'dingCMS', null, 'Y', null, '6a5d90af-8b8f-4613-9e08-40f90d2d8b39', null, null, null, 'bd_JobLock', 'dingCMS', 0, 'bd_JobLock', '0', '2019-06-06 16:42:42', 'N', 0 );
 insert into md_class ( modinfoclassname, createtime, parentclassid, ts, userdefclassname, iscreatesql, creator, id, help, bizitfimpclassname, description, name, refmodelname, industry, modifytime, dr, accessorclassname, tenantid, isprimary, resid, isauthen, keyattribute, fullclassname, classtype, returntype, componentid, isactive, modifier, stereotype, isextendbean, defaulttablename, versiontype, displayname, precise, fixedlength ) values ( null, '2019-06-06 16:42:40', null, '2019-06-06 16:48:41', null, 'Y', null, 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', null, null, null, 'JobLock', null, '0', '2019-06-06 16:47:53', 0, 'nc.md.model.access.javamap.POJOStyle', null, 'Y', null, 'Y', '8c3fe0d3-d814-423b-9a1a-d71ae1b61b17', 'com.ding.cms.entity.JobLock', 201, null, '6a5d90af-8b8f-4613-9e08-40f90d2d8b39', null, null, null, null, 'bd_joblock', 0, 'job锁', null, null );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-06 16:48:41', 0, null, 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'N', null, 'N', null, 'N', '8c3fe0d3-d814-423b-9a1a-d71ae1b61b17', null, 300, null, 'id', null, '0', null, null, 0, null, null, 'N', null, 'Y', 0, 'N', null, 'Y', 36, null, 'BS000010000100001051', 'N', null, 'N', 0, '主键', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-06 16:48:41', 0, null, 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'N', null, 'N', null, 'N', '6ed6da38-1a2c-43c0-982b-db2123db539d', null, 300, null, 'jobid', null, '0', null, null, 0, null, null, 'N', null, 'Y', 1, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, 'jobid', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-06 16:48:41', 0, null, 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'N', null, 'N', null, 'N', 'b2daf494-8408-4572-b11a-f841aa4459c0', null, 300, null, 'starttime', null, '0', null, null, 0, null, null, 'N', null, 'Y', 2, 'Y', null, 'Y', null, null, 'BS000010000100001033', 'N', null, 'N', 0, '开始时间', null, 'N' );
 insert into md_property ( dynamicattr, createtime, ts, visibility, dynamictable, classid, accesspower, attrmaxvalue, notserialize, creator, calculation, id, help, datatypestyle, description, name, refmodelname, industry, defaultvalue, modifytime, dr, accessorclassname, tenantid, hided, resid, isauthen, attrsequence, nullable, attrminvalue, isactive, attrlength, modifier, datatype, readonly, accesspowergroup, customattr, versiontype, displayname, precise, fixedlength ) values ( 'N', null, '2019-06-06 16:48:41', 0, null, 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'N', null, 'N', null, 'N', '6b736a07-4a5b-400b-9096-1970f3c605c8', null, 300, null, 'ip', null, '0', null, null, 0, null, null, 'N', null, 'Y', 3, 'Y', null, 'Y', 50, null, 'BS000010000100001001', 'N', null, 'N', 0, 'IP地址', null, 'N' );
 insert into md_table ( createtime, tenantid, resid, ts, isextendtable, resmodule, creator, fromsourcebmf, modifier, id, isactive, help, databaseid, description, name, versiontype, industry, displayname, modifytime, parenttable, dr ) values ( '2019-06-06 16:42:40', null, null, '2019-06-06 16:48:41', 'N', 'bd_JobLock', null, 'Y', null, 'bd_joblock', null, null, null, null, 'bd_joblock', 0, '0', 'job锁', '2019-06-06 16:47:53', null, 0 );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-06 16:48:41', null, 'bd_joblock@@PK@@', null, 'char', null, null, 'id', null, null, null, null, 0, null, 36, null, 'Y', 'N', 'Y', null, 0, null, 0, 'bd_joblock', '主键', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-06 16:48:41', null, 'bd_joblock@@@jobid', null, 'varchar', null, null, 'jobid', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 1, null, 0, 'bd_joblock', 'jobid', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-06 16:48:41', null, 'bd_joblock@@@starttime', null, 'datetime', null, null, 'starttime', null, null, null, null, 0, null, null, null, 'N', 'Y', 'Y', null, 2, null, 0, 'bd_joblock', '开始时间', null );
 insert into md_column ( createtime, forlocale, columntype, ts, creator, id, help, sqldatetype, groupid, description, name, incrementseed, incrementstep, defaultvalue, modifytime, dr, tenantid, columnlength, resid, pkey, nullable, isactive, modifier, columnsequence, identitied, versiontype, tableid, displayname, precise ) values ( null, 'N', 0, '2019-06-06 16:48:41', null, 'bd_joblock@@@ip', null, 'varchar', null, null, 'ip', null, null, null, null, 0, null, 50, null, 'N', 'Y', 'Y', null, 3, null, 0, 'bd_joblock', 'IP地址', null );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-06 16:48:41', 'bd_joblock@@@jobid', 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'bd_joblock', '6ed6da38-1a2c-43c0-982b-db2123db539d', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-06 16:48:41', 'bd_joblock@@PK@@', 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'bd_joblock', '8c3fe0d3-d814-423b-9a1a-d71ae1b61b17', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-06 16:48:41', 'bd_joblock@@@starttime', 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'bd_joblock', 'b2daf494-8408-4572-b11a-f841aa4459c0', 0 );
 insert into md_ormap ( tenantid, ts, columnid, classid, tableid, attributeid, dr ) values ( null, '2019-06-06 16:48:41', 'bd_joblock@@@ip', 'd4fcf716-9112-423e-b5fd-305d9c1e7ec5', 'bd_joblock', '6b736a07-4a5b-400b-9096-1970f3c605c8', 0 );
